# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  script:
#  - npm install postcss-cli postcss-uncss uncss
  - hugo --minify
  - gzip -k -6 -r public
  artifacts:
    paths:
    - public
  only:
  - master
