# Site settings
title: invirds
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Open source database of useful softwares. 
  Innovatively arranged, deeply searchable and convenient to use. 
  Objective presentation of information makes software comparison a breeze.
baseurl: ""
url: "https://invirds.gitlab.io"
author: "invirds team"

# twitter:
#   username: handle
#   card: summary
# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234

# logo: /assets/your-company-logo.png

# social:
#   name: fossbase # If the user or organization name differs from the site's name
#   links:
#     - https://twitter.com/fossbase
#     - https://www.facebook.com/fossbase
#     - https://www.linkedin.com/in/fossbase
#     - https://plus.google.com/+fossbase
#     - https://github.com/fossbase
#     - https://keybase.io/fossbase

# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234

# github_username:  jekyll

# Build settings
markdown: kramdown
exclude: ["README.md", "Gemfile", "Gemfile.lock"]

collections:
  software:
    output: true
    permalink: /softwares/:title/
    
defaults:
  -
    scope:
      path: ""
      type: "software"
    values:
      layout: "software"

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

# plugins:
#   - jekyll-sitemap
#   - jekyll-seo-tag
#   - jekyll-include-cache
