title: "Softorage" # required

baseURL: "https://softorage.com/" # required

languageCode: "en-us" # recommended

params:
  description: "Softorage is a software directory designed as a secure download service and information resource, with a focus on safety & respecting user privacy." # The one place for authentic downloads and all your software related information needs # required
  tagline: "The Software Directory." # required, recommended for SEO template (partials/seo.html)
  twitter: "Softorage" # optional, twitter handle; recommended for SEO template (partials/seo.html)
  fb_app_id: "170403084180809" # optional, for SEO template (partials/seo.html)
  image: "https://softorage.com/assets/favicon/Softorage-Logo-Profile.png" # optional, absolute path to logo image to be used for social media; resolution 200px x 200px to 1200px x 1200px
  search_target: "https://softorage.com/search?s" # optional, definition: where you wish to direct users with search term; used in SEO template {{ site.Params.search_target | safeHTML | jsonify }}={search_term_string}

author: 
  name: "Sanmay Joshi and Softorage contributors" # required
  email: "contact@softorage.com" # optional, used in default rss template : https://gohugo.io/templates/rss/#configure-rss

copyright: "Code licensed under Apache license 2.0. Unless otherwise noted, content licensed under CC-BY-SA-3.0 license." # optional, used in default rss template : https://gohugo.io/templates/rss/#configure-rss

taxonomies:
  category: "categories" # optional

frontmatter:
  date: ["date", "publishDate", "lastmod", ":git"] # adding ':git' at the end (of default format) makes the atom/rss feed to fetch dates from git, once enableGitInfo is set to true in 'config' file

enableRobotsTXT: true # optional, allows us to specify custom layout for robots.txt file
enableGitInfo: true # optional, allows us to use '.GitInfo' object. '.GitInfo' object allows us to leverage info from git for use in Hugo

# Allow HTML in markdown to be rendered
markup:
  goldmark:
    renderer:
      unsafe: true

googleAnalytics: "UA-154890683-1" # optional

# Define output formats # Optional
#outputs:
#  page:
#  - HTML
#  - AMP

