baseURL: "https://softorage.gitlab.io/"
languageCode: "en-us"
title: "Softorage"
params:
  description:
  author: Softorage team
  # tagline: # required in SEO template (partial/seo.html)
  # twitter: # required in SEO template (partial/seo.html)
  # image: # resolution 200px x 200px to 1200px x 1200px

taxonomies:
  category: categories

enableRobotsTXT: true
enableGitInfo: true
