title: "Softorage" # required

baseURL: "https://softorage.com/" # required

languageCode: "en-us" # recommended

# with this, Hugo notes some stats about website, which are then used by CSS processors
# build:
#   writeStats: true
  
# All privacy settings: https://gohugo.io/about/hugo-and-gdpr/#all-privacy-settings
# Explanations to all privacy settings: https://gohugo.io/about/hugo-and-gdpr/#the-privacy-settings-explained
privacy:
  disqus:
    disable: "false"
  googleAnalytics:
    anonymizeIP: "true" # 'true' makes it so the users' IP addresses are anonymized within Google Analytics
    disable: "false"
    respectDoNotTrack: "false" # 'true' makes the GA templates respect the “Do Not Track” HTTP header
    useSessionStorage: "false" # 'true' disables the use of Cookies and use Session Storage to Store the GA Client ID

params:
  description: "Softorage is a software directory designed as a secure download service and information resource, with a focus on safety & respecting user privacy." # The one place for authentic downloads and all your software related information needs # required
  tagline: "The Software Directory." # required, recommended for SEO template (partials/seo.html)
  twitter: "Softorage" # optional, twitter handle; recommended for SEO template (partials/seo.html)
  fb_app_id: "170403084180809" # optional, for SEO template (partials/seo.html)
  image: "https://softorage.com/assets/favicon/Softorage-Logo-Profile.png" # optional, absolute path to logo image to be used for social media; resolution 200px x 200px to 1200px x 1200px
  search_target: "https://softorage.com/search?s" # optional, definition: where you wish to direct users with search term; used in SEO template {{ site.Params.search_target | safeHTML | jsonify }}={search_term_string}
  social: 
    profiles: # social platforms you are present on. see supported ones here | highly recommended
      facebook: "https://www.facebook.com/Softorage"
      twitter: "https://twitter.com/Softorage"
      github: "https://github.com/Softorage"
      gitlab: "https://gitlab.com/Softorage"
      instagram: "https://www.instagram.com/softorage"
  cookieConsent: # we use OSANO Cookie Consent solution
    switch: "on" # accepts: on/off | decide whether you want to show a cookie consent dialog to your users | default: "off"
    type: "opt-out" # accepts: opt-in/opt-out/none | In opt-in, website doesn't employ cookies to user's computer unless user gives cosent to opt in. In opt-out, cookies are employed on user's computer and the user is given the choice to opt out of cookies. In none, cookies are employed on the user's computer and user is not given a choice in that regard. Refrain from using none, unless you have zero customers from EU or similar countries with privacy protecting laws. | no default
    revokable: false # a button to revoke cookie consent appears when user hover in bottom area of the screen, regardless whether user's country requires revertable cookie consent | default: true
    colors:
      banner:
        background: "#fafafa" # HEX | default: theme.nav
        text: "#343434" # HEX | default: theme.antinav
      button:
        background: "#3f5efb" # HEX | default: theme.clr2
        text: "#fbfbfb" # HEX | default: theme.nav
    content: # change the links below to appropriate url addresses
      message: | # no default
        For us, protection of your privacy isn't just a commitment, but passion. To ensure you get the best user experience, and to get an understanding of metrics, we use cookies with privacy protections like 'Anonymizing IP'. By continuing to use this site, you agree to the use of these cookies and that you have read and understood <a href='/legal/cookie-policy/'>Cookie Policy</a>, <a href='/legal/privacy-policy/'>Privacy Poilcy</a> and our <a href='/legal/terms-and-conditions/'>Terms and Conditions</a>.
      dismiss: "Okay. Got it!" # text on the button that dismisses the popup/banner | default: "Close"
      linkText: "Find more about cookies and how we take privacy very seriously, in our Privacy Policy." # this text appears after the message and is hyperlinked | default: "Learn more"
      linkURL: "/legal/privacy-policy/" # url of location where user should be directed when they click "Learn more".
      allow: "Allow cookies" # text on the button that allows cookies | default: "Allow"
      deny: "Decline" # text on the button that denies cookies | default: "Decline"
      policy: "Cookie Consent" # text that appears on the button, when user's country requires revokable cookie consent | default: "Cookie Consent"
  userExperience:
    googleAnalyticsLoading: "async" # accepts value: sync/async | determines whether Google Analytics JavaScript file loads 'Synchronously' or 'Asynchronously' | optional | default: "sync"

author: 
  name: "Sanmay Joshi and Softorage contributors" # required
  email: "contact@softorage.com" # optional, used in default rss template : https://gohugo.io/templates/rss/#configure-rss

copyright: "Code licensed under Apache license 2.0. Unless otherwise noted, content licensed under CC-BY-SA-3.0 license." # optional, used in default rss template : https://gohugo.io/templates/rss/#configure-rss

taxonomies:
  category: "categories" # optional

frontmatter:
  date: ["date", "publishDate", "lastmod", ":git"] # adding ':git' at the end (of default format) makes the atom/rss feed to fetch dates from git, once enableGitInfo is set to true in 'config' file

enableRobotsTXT: true # optional, allows us to specify custom layout for robots.txt file
enableGitInfo: true # optional, allows us to use '.GitInfo' object. '.GitInfo' object allows us to leverage info from git for use in Hugo

# Allow HTML in markdown to be rendered
markup:
  goldmark:
    renderer:
      unsafe: true

googleAnalytics: "UA-154890683-1" # optional

# Define output formats # Optional
#outputs:
#  page:
#  - HTML
#  - AMP

